# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2.1

git_config: &git_config
  name: configure git bot
  command: |
    if [ -z "$CIRCLE_PR_USERNAME" -a "$CIRCLE_USERNAME" != "dialog-bot" -a -n "$CIRCLE_USERNAME" ]
    then
      git config user.name "$GITHUB_BOT_USERNAME"
      git config user.email "$GITHUB_BOT_EMAIL"
    fi

executors:
  build-executor:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/code

jobs:
  dependencies:
    executor: build-executor
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: v1-dependencies-{{ checksum "build.gradle" }}
      - run:
          name: Download Dependencies
          command: ./gradlew dependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}
  build:
    executor: build-executor
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: v1-dependencies-{{ checksum "build.gradle" }}
      - run:
          name: Build
          command: ./gradlew build
  release:
    executor: build-executor
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - run:
          <<: *git_config
      - restore_cache:
          key: v1-dependencies-{{ checksum "build.gradle" }}
      - run:
          name: Change origin to push by bot
          command: |
            git remote set-url origin https://${GITHUB_BOT_TOKEN}@github.com/dialogs/api-schema.git
      - run:
          name: Release
          command: echo -ne '\n\n' | ./gradlew release
workflows:
  version: 2
  java-build-release:
    jobs:
      - dependencies     
      - build:
          requires:
            - dependencies
      - release:
          requires:
            - build
          filters:
            branches:
              only: master
