// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: authentication.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30004
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30004 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class AuthSession;
@class Config;
@class ForceReloadContacts;
@class ForceReloadDialogs;
@class ForceReloadHistory;
@class GPBDoubleValue;
@class GPBInt64Value;
@class GPBStringValue;
@class Peer;
@class User;
GPB_ENUM_FWD_DECLARE(Sex);

NS_ASSUME_NONNULL_BEGIN

#pragma mark - Enum PhoneActivationType

typedef GPB_ENUM(PhoneActivationType) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  PhoneActivationType_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  PhoneActivationType_PhoneActivationTypeUnknown = 0,
  PhoneActivationType_PhoneActivationTypeCode = 1,
  PhoneActivationType_PhoneActivationTypePassword = 2,
};

GPBEnumDescriptor *PhoneActivationType_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL PhoneActivationType_IsValidValue(int32_t value);

#pragma mark - Enum EmailActivationType

typedef GPB_ENUM(EmailActivationType) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  EmailActivationType_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  EmailActivationType_EmailActivationTypeUnknown = 0,
  EmailActivationType_EmailActivationTypeCode = 1,
  EmailActivationType_EmailActivationTypeOauth2 = 2,
  EmailActivationType_EmailActivationTypePassword = 3,
};

GPBEnumDescriptor *EmailActivationType_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL EmailActivationType_IsValidValue(int32_t value);

#pragma mark - Enum AuthExtraInfoType

typedef GPB_ENUM(AuthExtraInfoType) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  AuthExtraInfoType_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  AuthExtraInfoType_AuthExtraInfoTypeNone = 0,
  AuthExtraInfoType_AuthExtraInfoTypeNeedChangePassword = 1,
};

GPBEnumDescriptor *AuthExtraInfoType_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL AuthExtraInfoType_IsValidValue(int32_t value);

#pragma mark - Enum AuthHolder

/** / Holder of session */
typedef GPB_ENUM(AuthHolder) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  AuthHolder_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  AuthHolder_AuthHolderUnknown = 0,
  AuthHolder_AuthHolderThisdevice = 1,
  AuthHolder_AuthHolderOtherdevice = 2,
};

GPBEnumDescriptor *AuthHolder_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL AuthHolder_IsValidValue(int32_t value);

#pragma mark - AuthenticationRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
GPB_FINAL @interface AuthenticationRoot : GPBRootObject
@end

#pragma mark - RequestStartPhoneAuth

typedef GPB_ENUM(RequestStartPhoneAuth_FieldNumber) {
  RequestStartPhoneAuth_FieldNumber_PhoneNumber = 1,
  RequestStartPhoneAuth_FieldNumber_TimeZone = 2,
  RequestStartPhoneAuth_FieldNumber_PreferredLanguagesArray = 3,
};

/**
 * Start Phone Activation
 **/
GPB_FINAL @interface RequestStartPhoneAuth : GPBMessage

@property(nonatomic, readwrite) int64_t phoneNumber;

/** * Your timezone * */
@property(nonatomic, readwrite, strong, null_resettable) GPBStringValue *timeZone;
/** Test to see if @c timeZone has been set. */
@property(nonatomic, readwrite) BOOL hasTimeZone;

/** * First language from this array will be used for some notifications from server * */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *preferredLanguagesArray;
/** The number of items in @c preferredLanguagesArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger preferredLanguagesArray_Count;

@end

#pragma mark - ResponseStartPhoneAuth

typedef GPB_ENUM(ResponseStartPhoneAuth_FieldNumber) {
  ResponseStartPhoneAuth_FieldNumber_TransactionHash = 1,
  ResponseStartPhoneAuth_FieldNumber_IsRegistered = 2,
  ResponseStartPhoneAuth_FieldNumber_ActivationType = 3,
};

GPB_FINAL @interface ResponseStartPhoneAuth : GPBMessage

/** * Hash of authorization transaction * */
@property(nonatomic, readwrite, copy, null_resettable) NSString *transactionHash;

@property(nonatomic, readwrite) BOOL isRegistered;

/** * Code or password - call ValidateCode if code * */
@property(nonatomic, readwrite) PhoneActivationType activationType;

@end

/**
 * Fetches the raw value of a @c ResponseStartPhoneAuth's @c activationType property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t ResponseStartPhoneAuth_ActivationType_RawValue(ResponseStartPhoneAuth *message);
/**
 * Sets the raw value of an @c ResponseStartPhoneAuth's @c activationType property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetResponseStartPhoneAuth_ActivationType_RawValue(ResponseStartPhoneAuth *message, int32_t value);

#pragma mark - RequestSendCodeByPhoneCall

typedef GPB_ENUM(RequestSendCodeByPhoneCall_FieldNumber) {
  RequestSendCodeByPhoneCall_FieldNumber_TransactionHash = 1,
};

/**
 * Dial phone and dictate auth code
 **/
GPB_FINAL @interface RequestSendCodeByPhoneCall : GPBMessage

/** / Hash from ResponseStartPhoneAuth */
@property(nonatomic, readwrite, copy, null_resettable) NSString *transactionHash;

@end

#pragma mark - RequestStartEmailAuth

typedef GPB_ENUM(RequestStartEmailAuth_FieldNumber) {
  RequestStartEmailAuth_FieldNumber_Email = 1,
  RequestStartEmailAuth_FieldNumber_TimeZone = 2,
  RequestStartEmailAuth_FieldNumber_PreferredLanguagesArray = 3,
};

/**
 * Start EMail Activation
 **/
GPB_FINAL @interface RequestStartEmailAuth : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *email;

/** * Your timezone * */
@property(nonatomic, readwrite, strong, null_resettable) GPBStringValue *timeZone;
/** Test to see if @c timeZone has been set. */
@property(nonatomic, readwrite) BOOL hasTimeZone;

/** * First language from this array will be used for some notifications from server * */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *preferredLanguagesArray;
/** The number of items in @c preferredLanguagesArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger preferredLanguagesArray_Count;

@end

#pragma mark - ResponseStartEmailAuth

typedef GPB_ENUM(ResponseStartEmailAuth_FieldNumber) {
  ResponseStartEmailAuth_FieldNumber_TransactionHash = 1,
  ResponseStartEmailAuth_FieldNumber_IsRegistered = 2,
  ResponseStartEmailAuth_FieldNumber_ActivationType = 3,
};

GPB_FINAL @interface ResponseStartEmailAuth : GPBMessage

/** * Hash of authorization transaction * */
@property(nonatomic, readwrite, copy, null_resettable) NSString *transactionHash;

@property(nonatomic, readwrite) BOOL isRegistered;

/** * Code or password - call ValidateCode if code * */
@property(nonatomic, readwrite) EmailActivationType activationType;

@end

/**
 * Fetches the raw value of a @c ResponseStartEmailAuth's @c activationType property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t ResponseStartEmailAuth_ActivationType_RawValue(ResponseStartEmailAuth *message);
/**
 * Sets the raw value of an @c ResponseStartEmailAuth's @c activationType property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetResponseStartEmailAuth_ActivationType_RawValue(ResponseStartEmailAuth *message, int32_t value);

#pragma mark - RequestStartCertificateAuth

typedef GPB_ENUM(RequestStartCertificateAuth_FieldNumber) {
  RequestStartCertificateAuth_FieldNumber_Name = 1,
  RequestStartCertificateAuth_FieldNumber_TimeZone = 2,
  RequestStartCertificateAuth_FieldNumber_PreferredLanguagesArray = 3,
};

GPB_FINAL @interface RequestStartCertificateAuth : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *name;

@property(nonatomic, readwrite, strong, null_resettable) GPBStringValue *timeZone;
/** Test to see if @c timeZone has been set. */
@property(nonatomic, readwrite) BOOL hasTimeZone;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *preferredLanguagesArray;
/** The number of items in @c preferredLanguagesArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger preferredLanguagesArray_Count;

@end

#pragma mark - RequestStartTokenAuth

typedef GPB_ENUM(RequestStartTokenAuth_FieldNumber) {
  RequestStartTokenAuth_FieldNumber_Token = 1,
  RequestStartTokenAuth_FieldNumber_TimeZone = 2,
  RequestStartTokenAuth_FieldNumber_PreferredLanguagesArray = 3,
};

/**
 * Starting token-based login - to authorize bot
 **/
GPB_FINAL @interface RequestStartTokenAuth : GPBMessage

/** * Token received from BotFather * */
@property(nonatomic, readwrite, copy, null_resettable) NSString *token;

/** * Your timezone * */
@property(nonatomic, readwrite, strong, null_resettable) GPBStringValue *timeZone;
/** Test to see if @c timeZone has been set. */
@property(nonatomic, readwrite) BOOL hasTimeZone;

/** * First language from this array will be used for some notifications from server * */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *preferredLanguagesArray;
/** The number of items in @c preferredLanguagesArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger preferredLanguagesArray_Count;

@end

#pragma mark - RequestStartUsernameAuth

typedef GPB_ENUM(RequestStartUsernameAuth_FieldNumber) {
  RequestStartUsernameAuth_FieldNumber_Username = 1,
  RequestStartUsernameAuth_FieldNumber_TimeZone = 2,
  RequestStartUsernameAuth_FieldNumber_PreferredLanguagesArray = 3,
};

/**
 * Starting Login Authentication
 **/
GPB_FINAL @interface RequestStartUsernameAuth : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *username;

@property(nonatomic, readwrite, strong, null_resettable) GPBStringValue *timeZone;
/** Test to see if @c timeZone has been set. */
@property(nonatomic, readwrite) BOOL hasTimeZone;

/** * First language from this array will be used for some notifications from server * */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *preferredLanguagesArray;
/** The number of items in @c preferredLanguagesArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger preferredLanguagesArray_Count;

@end

#pragma mark - ResponseStartUsernameAuth

typedef GPB_ENUM(ResponseStartUsernameAuth_FieldNumber) {
  ResponseStartUsernameAuth_FieldNumber_TransactionHash = 1,
  ResponseStartUsernameAuth_FieldNumber_IsRegistered = 2,
};

GPB_FINAL @interface ResponseStartUsernameAuth : GPBMessage

/** * Hash of authorization transaction * */
@property(nonatomic, readwrite, copy, null_resettable) NSString *transactionHash;

@property(nonatomic, readwrite) BOOL isRegistered;

@end

#pragma mark - RequestApplyExternalSessionAuth

typedef GPB_ENUM(RequestApplyExternalSessionAuth_FieldNumber) {
  RequestApplyExternalSessionAuth_FieldNumber_SessionId = 1,
};

/**
 * Apply external session to authorize user
 **/
GPB_FINAL @interface RequestApplyExternalSessionAuth : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *sessionId;

@end

#pragma mark - RequestGetIdToken

typedef GPB_ENUM(RequestGetIdToken_FieldNumber) {
  RequestGetIdToken_FieldNumber_Service = 1,
};

/**
 * Get Id Token for external system
 **/
GPB_FINAL @interface RequestGetIdToken : GPBMessage

/** * service alias token is intended for * */
@property(nonatomic, readwrite, copy, null_resettable) NSString *service;

@end

#pragma mark - ResponseGetIdToken

typedef GPB_ENUM(ResponseGetIdToken_FieldNumber) {
  ResponseGetIdToken_FieldNumber_Token = 1,
  ResponseGetIdToken_FieldNumber_ExpirationDate = 2,
};

/**
 * Get Id Token for external system
 **/
GPB_FINAL @interface ResponseGetIdToken : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *token;

/** * Unix time stamp * */
@property(nonatomic, readwrite) int64_t expirationDate;

@end

#pragma mark - RequestStartAuthTransaction

typedef GPB_ENUM(RequestStartAuthTransaction_FieldNumber) {
  RequestStartAuthTransaction_FieldNumber_TimeZone = 1,
  RequestStartAuthTransaction_FieldNumber_PreferredLanguagesArray = 2,
};

/**
 * Start Authentication/Authorization via external oAuth2/OpenID SSO Provider
 **/
GPB_FINAL @interface RequestStartAuthTransaction : GPBMessage

/** * Client timezone * */
@property(nonatomic, readwrite, strong, null_resettable) GPBStringValue *timeZone;
/** Test to see if @c timeZone has been set. */
@property(nonatomic, readwrite) BOOL hasTimeZone;

/** * First language from this array will be used for some notifications from server * */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *preferredLanguagesArray;
/** The number of items in @c preferredLanguagesArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger preferredLanguagesArray_Count;

@end

#pragma mark - ResponseStartAuthTransaction

typedef GPB_ENUM(ResponseStartAuthTransaction_FieldNumber) {
  ResponseStartAuthTransaction_FieldNumber_TransactionHash = 1,
};

GPB_FINAL @interface ResponseStartAuthTransaction : GPBMessage

/** * Hash of authorization transaction * */
@property(nonatomic, readwrite, copy, null_resettable) NSString *transactionHash;

@end

#pragma mark - RequestValidateCode

typedef GPB_ENUM(RequestValidateCode_FieldNumber) {
  RequestValidateCode_FieldNumber_TransactionHash = 1,
  RequestValidateCode_FieldNumber_Code = 2,
};

/**
 * Performing user sign in.
 **/
GPB_FINAL @interface RequestValidateCode : GPBMessage

/** * Hash of the authorization transaction * */
@property(nonatomic, readwrite, copy, null_resettable) NSString *transactionHash;

/** / Authorization code */
@property(nonatomic, readwrite, copy, null_resettable) NSString *code;

@end

#pragma mark - RequestResendCode

typedef GPB_ENUM(RequestResendCode_FieldNumber) {
  RequestResendCode_FieldNumber_TransactionHash = 1,
};

/**
 * Performs code resend
 **/
GPB_FINAL @interface RequestResendCode : GPBMessage

/** * Hash of the authorization transaction * */
@property(nonatomic, readwrite, copy, null_resettable) NSString *transactionHash;

@end

#pragma mark - RequestValidatePassword

typedef GPB_ENUM(RequestValidatePassword_FieldNumber) {
  RequestValidatePassword_FieldNumber_TransactionHash = 1,
  RequestValidatePassword_FieldNumber_Password = 2,
};

/**
 * Validation of account password
 **/
GPB_FINAL @interface RequestValidatePassword : GPBMessage

/** * Hash of the authorization transaction * */
@property(nonatomic, readwrite, copy, null_resettable) NSString *transactionHash;

@property(nonatomic, readwrite, copy, null_resettable) NSString *password;

@end

#pragma mark - RequestGetOAuth2Params

typedef GPB_ENUM(RequestGetOAuth2Params_FieldNumber) {
  RequestGetOAuth2Params_FieldNumber_TransactionHash = 1,
  RequestGetOAuth2Params_FieldNumber_RedirectURL = 2,
};

/**
 * Loading OAuth2 Parameters
 **/
GPB_FINAL @interface RequestGetOAuth2Params : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *transactionHash;

@property(nonatomic, readwrite, copy, null_resettable) NSString *redirectURL;

@end

#pragma mark - ResponseGetOAuth2Params

typedef GPB_ENUM(ResponseGetOAuth2Params_FieldNumber) {
  ResponseGetOAuth2Params_FieldNumber_AuthURL = 1,
};

/**
 * / Redirect url result
 **/
GPB_FINAL @interface ResponseGetOAuth2Params : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *authURL;

@end

#pragma mark - RequestCompleteOAuth2

typedef GPB_ENUM(RequestCompleteOAuth2_FieldNumber) {
  RequestCompleteOAuth2_FieldNumber_TransactionHash = 1,
  RequestCompleteOAuth2_FieldNumber_Code = 2,
};

/**
 * Complete OAuth2 Authentication
 **/
GPB_FINAL @interface RequestCompleteOAuth2 : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *transactionHash;

@property(nonatomic, readwrite, copy, null_resettable) NSString *code;

@end

#pragma mark - RequestSignUp

typedef GPB_ENUM(RequestSignUp_FieldNumber) {
  RequestSignUp_FieldNumber_TransactionHash = 1,
  RequestSignUp_FieldNumber_Name = 2,
  RequestSignUp_FieldNumber_Sex = 3,
  RequestSignUp_FieldNumber_Password = 4,
};

/**
 * Perform user SignUp
 **/
GPB_FINAL @interface RequestSignUp : GPBMessage

/** * Hash of the authorization transaction * */
@property(nonatomic, readwrite, copy, null_resettable) NSString *transactionHash;

/** Your name */
@property(nonatomic, readwrite, copy, null_resettable) NSString *name;

@property(nonatomic, readwrite) enum Sex sex;

@property(nonatomic, readwrite, strong, null_resettable) GPBStringValue *password;
/** Test to see if @c password has been set. */
@property(nonatomic, readwrite) BOOL hasPassword;

@end

/**
 * Fetches the raw value of a @c RequestSignUp's @c sex property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t RequestSignUp_Sex_RawValue(RequestSignUp *message);
/**
 * Sets the raw value of an @c RequestSignUp's @c sex property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetRequestSignUp_Sex_RawValue(RequestSignUp *message, int32_t value);

#pragma mark - ResponseAuth

typedef GPB_ENUM(ResponseAuth_FieldNumber) {
  ResponseAuth_FieldNumber_User = 2,
  ResponseAuth_FieldNumber_Config = 3,
  ResponseAuth_FieldNumber_ConfigHash = 4,
  ResponseAuth_FieldNumber_ExtraInfoArray = 5,
};

/**
 * Authentication result
 **/
GPB_FINAL @interface ResponseAuth : GPBMessage

/** / Registered/authorized user */
@property(nonatomic, readwrite, strong, null_resettable) User *user;
/** Test to see if @c user has been set. */
@property(nonatomic, readwrite) BOOL hasUser;

/** / Config for that user */
@property(nonatomic, readwrite, strong, null_resettable) Config *config;
/** Test to see if @c config has been set. */
@property(nonatomic, readwrite) BOOL hasConfig;

/** / Hash of config to later usage */
@property(nonatomic, readwrite, strong, null_resettable) GPBInt64Value *configHash;
/** Test to see if @c configHash has been set. */
@property(nonatomic, readwrite) BOOL hasConfigHash;

// |extraInfoArray| contains |AuthExtraInfoType|
@property(nonatomic, readwrite, strong, null_resettable) GPBEnumArray *extraInfoArray;
/** The number of items in @c extraInfoArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger extraInfoArray_Count;

@end

#pragma mark - AuthSession

typedef GPB_ENUM(AuthSession_FieldNumber) {
  AuthSession_FieldNumber_Id_p = 1,
  AuthSession_FieldNumber_AuthHolder = 2,
  AuthSession_FieldNumber_AppId = 3,
  AuthSession_FieldNumber_AppTitle = 4,
  AuthSession_FieldNumber_DeviceTitle = 5,
  AuthSession_FieldNumber_AuthTime = 6,
  AuthSession_FieldNumber_AuthLocation = 7,
  AuthSession_FieldNumber_Latitude = 8,
  AuthSession_FieldNumber_Longitude = 9,
};

/**
 * Authentication session
 **/
GPB_FINAL @interface AuthSession : GPBMessage

/** / Unuque ID of session */
@property(nonatomic, readwrite, copy, null_resettable) NSString *id_p;

/** / holder of session. 1 - this device, 2 - other. */
@property(nonatomic, readwrite) AuthHolder authHolder;

/** / Application Id that you set during authorization */
@property(nonatomic, readwrite) int32_t appId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *appTitle;

@property(nonatomic, readwrite, copy, null_resettable) NSString *deviceTitle;

/** / Time of session creating */
@property(nonatomic, readwrite) int32_t authTime;

/** / Two-letter country code of session create */
@property(nonatomic, readwrite, copy, null_resettable) NSString *authLocation;

@property(nonatomic, readwrite, strong, null_resettable) GPBDoubleValue *latitude;
/** Test to see if @c latitude has been set. */
@property(nonatomic, readwrite) BOOL hasLatitude;

@property(nonatomic, readwrite, strong, null_resettable) GPBDoubleValue *longitude;
/** Test to see if @c longitude has been set. */
@property(nonatomic, readwrite) BOOL hasLongitude;

@end

/**
 * Fetches the raw value of a @c AuthSession's @c authHolder property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t AuthSession_AuthHolder_RawValue(AuthSession *message);
/**
 * Sets the raw value of an @c AuthSession's @c authHolder property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetAuthSession_AuthHolder_RawValue(AuthSession *message, int32_t value);

#pragma mark - RequestGetAuthSessions

/**
 * Getting of all active user's authentication sessions
 **/
GPB_FINAL @interface RequestGetAuthSessions : GPBMessage

@end

#pragma mark - ResponseGetAuthSessions

typedef GPB_ENUM(ResponseGetAuthSessions_FieldNumber) {
  ResponseGetAuthSessions_FieldNumber_UserAuthsArray = 1,
};

GPB_FINAL @interface ResponseGetAuthSessions : GPBMessage

/** / Active user's sessions */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<AuthSession*> *userAuthsArray;
/** The number of items in @c userAuthsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger userAuthsArray_Count;

@end

#pragma mark - RequestTerminateSession

typedef GPB_ENUM(RequestTerminateSession_FieldNumber) {
  RequestTerminateSession_FieldNumber_Id_p = 1,
};

/**
 * SignOut on specified user's session
 **/
GPB_FINAL @interface RequestTerminateSession : GPBMessage

/** / Session id */
@property(nonatomic, readwrite, copy, null_resettable) NSString *id_p;

@end

#pragma mark - RequestTerminateAllSessions

/**
 * SignOut on all exept current sessions
 **/
GPB_FINAL @interface RequestTerminateAllSessions : GPBMessage

@end

#pragma mark - RequestSignOut

/**
 * SignOut current session
 **/
GPB_FINAL @interface RequestSignOut : GPBMessage

@end

#pragma mark - ForceReloadField

typedef GPB_ENUM(ForceReloadField_FieldNumber) {
  ForceReloadField_FieldNumber_ForceReloadDialogs = 1,
  ForceReloadField_FieldNumber_ForceReloadContacts = 2,
  ForceReloadField_FieldNumber_ForceReloadHistory = 3,
};

typedef GPB_ENUM(ForceReloadField_Body_OneOfCase) {
  ForceReloadField_Body_OneOfCase_GPBUnsetOneOfCase = 0,
  ForceReloadField_Body_OneOfCase_ForceReloadDialogs = 1,
  ForceReloadField_Body_OneOfCase_ForceReloadContacts = 2,
  ForceReloadField_Body_OneOfCase_ForceReloadHistory = 3,
};

/**
 * *
 * Notification to force client to reload some entities from server
 * Just for old clients. Should be ignore.
 **/
GPB_FINAL @interface ForceReloadField : GPBMessage

@property(nonatomic, readonly) ForceReloadField_Body_OneOfCase bodyOneOfCase;

@property(nonatomic, readwrite, strong, null_resettable) ForceReloadDialogs *forceReloadDialogs;

@property(nonatomic, readwrite, strong, null_resettable) ForceReloadContacts *forceReloadContacts;

@property(nonatomic, readwrite, strong, null_resettable) ForceReloadHistory *forceReloadHistory;

@end

/**
 * Clears whatever value was set for the oneof 'body'.
 **/
void ForceReloadField_ClearBodyOneOfCase(ForceReloadField *message);

#pragma mark - ForceReloadDialogs

/**
 * Tells the client to clear dialogs and load them again
 **/
GPB_FINAL @interface ForceReloadDialogs : GPBMessage

@end

#pragma mark - ForceReloadContacts

/**
 * Tells the client to clear contacts and load them again
 **/
GPB_FINAL @interface ForceReloadContacts : GPBMessage

@end

#pragma mark - ForceReloadHistory

typedef GPB_ENUM(ForceReloadHistory_FieldNumber) {
  ForceReloadHistory_FieldNumber_Peer = 1,
};

/**
 * Tells the client to clear the specified conversation and load it again
 * peer the peer whose history should be reloaded
 **/
GPB_FINAL @interface ForceReloadHistory : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) Peer *peer;
/** Test to see if @c peer has been set. */
@property(nonatomic, readwrite) BOOL hasPeer;

@end

#pragma mark - RequestChangePassword

typedef GPB_ENUM(RequestChangePassword_FieldNumber) {
  RequestChangePassword_FieldNumber_OldPassword = 1,
  RequestChangePassword_FieldNumber_NewPassword = 2,
};

GPB_FINAL @interface RequestChangePassword : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *oldPassword;

@property(nonatomic, readwrite, copy, null_resettable) NSString *newPassword NS_RETURNS_NOT_RETAINED;

@end

#pragma mark - RequestGetSelf

GPB_FINAL @interface RequestGetSelf : GPBMessage

@end

#pragma mark - ResponseGetSelf

typedef GPB_ENUM(ResponseGetSelf_FieldNumber) {
  ResponseGetSelf_FieldNumber_User = 1,
};

GPB_FINAL @interface ResponseGetSelf : GPBMessage

/** / Registered/authorized user */
@property(nonatomic, readwrite, strong, null_resettable) User *user;
/** Test to see if @c user has been set. */
@property(nonatomic, readwrite) BOOL hasUser;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
