// Code generated by gRPC proto compiler.  DO NOT EDIT!
// source: config_sync.proto

#if !defined(GPB_GRPC_FORWARD_DECLARE_MESSAGE_PROTO) || !GPB_GRPC_FORWARD_DECLARE_MESSAGE_PROTO
#import "ConfigSync.pbobjc.h"
#endif

#if !defined(GPB_GRPC_PROTOCOL_ONLY) || !GPB_GRPC_PROTOCOL_ONLY
#import <ProtoRPC/ProtoService.h>
#import <ProtoRPC/ProtoRPCLegacy.h>
#import <RxLibrary/GRXWriteable.h>
#import <RxLibrary/GRXWriter.h>
#endif

@class GPBEmpty;
@class RequestChangeSettings;
@class RequestEditParameter;
@class RequestFeatureFlags;
@class RequestGetParameters;
@class RequestGetSettings;
@class ResponseFeatureFlags;
@class ResponseGetParameters;
@class ResponseGetSettings;

#if !defined(GPB_GRPC_FORWARD_DECLARE_MESSAGE_PROTO) || !GPB_GRPC_FORWARD_DECLARE_MESSAGE_PROTO
  #import "Wrappers.pbobjc.h"
  #import "Empty.pbobjc.h"
  #import "Annotations.pbobjc.h"
  #import "Definitions.pbobjc.h"
  #import "Scalapb.pbobjc.h"
#endif

@class GRPCUnaryProtoCall;
@class GRPCStreamingProtoCall;
@class GRPCCallOptions;
@protocol GRPCProtoResponseHandler;
@class GRPCProtoCall;


NS_ASSUME_NONNULL_BEGIN

@protocol ConfigSync2 <NSObject>

#pragma mark GetSettings(RequestGetSettings) returns (ResponseGetSettings)

/**
 * / Метод получения настроек клиентских приложений
 */
- (GRPCUnaryProtoCall *)getSettingsWithMessage:(RequestGetSettings *)message responseHandler:(id<GRPCProtoResponseHandler>)handler callOptions:(GRPCCallOptions *_Nullable)callOptions;

#pragma mark ChangeSettings(RequestChangeSettings) returns (Empty)

/**
 * / Метод изменения настроек клиентских приложений
 */
- (GRPCUnaryProtoCall *)changeSettingsWithMessage:(RequestChangeSettings *)message responseHandler:(id<GRPCProtoResponseHandler>)handler callOptions:(GRPCCallOptions *_Nullable)callOptions;

#pragma mark GetParameters(RequestGetParameters) returns (ResponseGetParameters)

/**
 * / Метод получения списка пользовательских параметров
 */
- (GRPCUnaryProtoCall *)getParametersWithMessage:(RequestGetParameters *)message responseHandler:(id<GRPCProtoResponseHandler>)handler callOptions:(GRPCCallOptions *_Nullable)callOptions;

#pragma mark EditParameter(RequestEditParameter) returns (Empty)

/**
 * / Метод изменения пользовательских параметров
 */
- (GRPCUnaryProtoCall *)editParameterWithMessage:(RequestEditParameter *)message responseHandler:(id<GRPCProtoResponseHandler>)handler callOptions:(GRPCCallOptions *_Nullable)callOptions;

#pragma mark FeatureFlags(RequestFeatureFlags) returns (ResponseFeatureFlags)

/**
 * / Метод получения флагов конфигурации сервера
 */
- (GRPCUnaryProtoCall *)featureFlagsWithMessage:(RequestFeatureFlags *)message responseHandler:(id<GRPCProtoResponseHandler>)handler callOptions:(GRPCCallOptions *_Nullable)callOptions;

@end

/**
 * The methods in this protocol belong to a set of old APIs that have been deprecated. They do not
 * recognize call options provided in the initializer. Using the v2 protocol is recommended.
 */
@protocol ConfigSync <NSObject>

#pragma mark GetSettings(RequestGetSettings) returns (ResponseGetSettings)

/**
 * / Метод получения настроек клиентских приложений
 *
 * This method belongs to a set of APIs that have been deprecated. Using the v2 API is recommended.
 */
- (void)getSettingsWithRequest:(RequestGetSettings *)request handler:(void(^)(ResponseGetSettings *_Nullable response, NSError *_Nullable error))handler;

/**
 * / Метод получения настроек клиентских приложений
 *
 * This method belongs to a set of APIs that have been deprecated. Using the v2 API is recommended.
 */
- (GRPCProtoCall *)RPCToGetSettingsWithRequest:(RequestGetSettings *)request handler:(void(^)(ResponseGetSettings *_Nullable response, NSError *_Nullable error))handler;


#pragma mark ChangeSettings(RequestChangeSettings) returns (Empty)

/**
 * / Метод изменения настроек клиентских приложений
 *
 * This method belongs to a set of APIs that have been deprecated. Using the v2 API is recommended.
 */
- (void)changeSettingsWithRequest:(RequestChangeSettings *)request handler:(void(^)(GPBEmpty *_Nullable response, NSError *_Nullable error))handler;

/**
 * / Метод изменения настроек клиентских приложений
 *
 * This method belongs to a set of APIs that have been deprecated. Using the v2 API is recommended.
 */
- (GRPCProtoCall *)RPCToChangeSettingsWithRequest:(RequestChangeSettings *)request handler:(void(^)(GPBEmpty *_Nullable response, NSError *_Nullable error))handler;


#pragma mark GetParameters(RequestGetParameters) returns (ResponseGetParameters)

/**
 * / Метод получения списка пользовательских параметров
 *
 * This method belongs to a set of APIs that have been deprecated. Using the v2 API is recommended.
 */
- (void)getParametersWithRequest:(RequestGetParameters *)request handler:(void(^)(ResponseGetParameters *_Nullable response, NSError *_Nullable error))handler;

/**
 * / Метод получения списка пользовательских параметров
 *
 * This method belongs to a set of APIs that have been deprecated. Using the v2 API is recommended.
 */
- (GRPCProtoCall *)RPCToGetParametersWithRequest:(RequestGetParameters *)request handler:(void(^)(ResponseGetParameters *_Nullable response, NSError *_Nullable error))handler;


#pragma mark EditParameter(RequestEditParameter) returns (Empty)

/**
 * / Метод изменения пользовательских параметров
 *
 * This method belongs to a set of APIs that have been deprecated. Using the v2 API is recommended.
 */
- (void)editParameterWithRequest:(RequestEditParameter *)request handler:(void(^)(GPBEmpty *_Nullable response, NSError *_Nullable error))handler;

/**
 * / Метод изменения пользовательских параметров
 *
 * This method belongs to a set of APIs that have been deprecated. Using the v2 API is recommended.
 */
- (GRPCProtoCall *)RPCToEditParameterWithRequest:(RequestEditParameter *)request handler:(void(^)(GPBEmpty *_Nullable response, NSError *_Nullable error))handler;


#pragma mark FeatureFlags(RequestFeatureFlags) returns (ResponseFeatureFlags)

/**
 * / Метод получения флагов конфигурации сервера
 *
 * This method belongs to a set of APIs that have been deprecated. Using the v2 API is recommended.
 */
- (void)featureFlagsWithRequest:(RequestFeatureFlags *)request handler:(void(^)(ResponseFeatureFlags *_Nullable response, NSError *_Nullable error))handler;

/**
 * / Метод получения флагов конфигурации сервера
 *
 * This method belongs to a set of APIs that have been deprecated. Using the v2 API is recommended.
 */
- (GRPCProtoCall *)RPCToFeatureFlagsWithRequest:(RequestFeatureFlags *)request handler:(void(^)(ResponseFeatureFlags *_Nullable response, NSError *_Nullable error))handler;


@end


#if !defined(GPB_GRPC_PROTOCOL_ONLY) || !GPB_GRPC_PROTOCOL_ONLY
/**
 * Basic service implementation, over gRPC, that only does
 * marshalling and parsing.
 */
@interface ConfigSync : GRPCProtoService<ConfigSync2, ConfigSync>
- (instancetype)initWithHost:(NSString *)host callOptions:(GRPCCallOptions *_Nullable)callOptions NS_DESIGNATED_INITIALIZER;
+ (instancetype)serviceWithHost:(NSString *)host callOptions:(GRPCCallOptions *_Nullable)callOptions;
// The following methods belong to a set of old APIs that have been deprecated.
- (instancetype)initWithHost:(NSString *)host;
+ (instancetype)serviceWithHost:(NSString *)host;
@end
#endif

NS_ASSUME_NONNULL_END

