// Code generated by gRPC proto compiler.  DO NOT EDIT!
// source: drafts.proto

#if !defined(GPB_GRPC_FORWARD_DECLARE_MESSAGE_PROTO) || !GPB_GRPC_FORWARD_DECLARE_MESSAGE_PROTO
#import "Drafts.pbobjc.h"
#endif

#if !defined(GPB_GRPC_PROTOCOL_ONLY) || !GPB_GRPC_PROTOCOL_ONLY
#import <ProtoRPC/ProtoService.h>
#import <ProtoRPC/ProtoRPCLegacy.h>
#import <RxLibrary/GRXWriteable.h>
#import <RxLibrary/GRXWriter.h>
#endif

@class LoadDraftsRequest;
@class LoadDraftsResponse;
@class SaveDraftsRequest;
@class SaveDraftsResponse;

#if !defined(GPB_GRPC_FORWARD_DECLARE_MESSAGE_PROTO) || !GPB_GRPC_FORWARD_DECLARE_MESSAGE_PROTO
  #import "Messaging.pbobjc.h"
  #import "Peers.pbobjc.h"
#endif

@class GRPCUnaryProtoCall;
@class GRPCStreamingProtoCall;
@class GRPCCallOptions;
@protocol GRPCProtoResponseHandler;
@class GRPCProtoCall;


NS_ASSUME_NONNULL_BEGIN

@protocol DraftsService2 <NSObject>

#pragma mark LoadDrafts(LoadDraftsRequest) returns (LoadDraftsResponse)

- (GRPCUnaryProtoCall *)loadDraftsWithMessage:(LoadDraftsRequest *)message responseHandler:(id<GRPCProtoResponseHandler>)handler callOptions:(GRPCCallOptions *_Nullable)callOptions;

#pragma mark SaveDrafts(SaveDraftsRequest) returns (SaveDraftsResponse)

- (GRPCUnaryProtoCall *)saveDraftsWithMessage:(SaveDraftsRequest *)message responseHandler:(id<GRPCProtoResponseHandler>)handler callOptions:(GRPCCallOptions *_Nullable)callOptions;

@end

/**
 * The methods in this protocol belong to a set of old APIs that have been deprecated. They do not
 * recognize call options provided in the initializer. Using the v2 protocol is recommended.
 */
@protocol DraftsService <NSObject>

#pragma mark LoadDrafts(LoadDraftsRequest) returns (LoadDraftsResponse)

- (void)loadDraftsWithRequest:(LoadDraftsRequest *)request handler:(void(^)(LoadDraftsResponse *_Nullable response, NSError *_Nullable error))handler;

- (GRPCProtoCall *)RPCToLoadDraftsWithRequest:(LoadDraftsRequest *)request handler:(void(^)(LoadDraftsResponse *_Nullable response, NSError *_Nullable error))handler;


#pragma mark SaveDrafts(SaveDraftsRequest) returns (SaveDraftsResponse)

- (void)saveDraftsWithRequest:(SaveDraftsRequest *)request handler:(void(^)(SaveDraftsResponse *_Nullable response, NSError *_Nullable error))handler;

- (GRPCProtoCall *)RPCToSaveDraftsWithRequest:(SaveDraftsRequest *)request handler:(void(^)(SaveDraftsResponse *_Nullable response, NSError *_Nullable error))handler;


@end


#if !defined(GPB_GRPC_PROTOCOL_ONLY) || !GPB_GRPC_PROTOCOL_ONLY
/**
 * Basic service implementation, over gRPC, that only does
 * marshalling and parsing.
 */
@interface DraftsService : GRPCProtoService<DraftsService2, DraftsService>
- (instancetype)initWithHost:(NSString *)host callOptions:(GRPCCallOptions *_Nullable)callOptions NS_DESIGNATED_INITIALIZER;
+ (instancetype)serviceWithHost:(NSString *)host callOptions:(GRPCCallOptions *_Nullable)callOptions;
// The following methods belong to a set of old APIs that have been deprecated.
- (instancetype)initWithHost:(NSString *)host;
+ (instancetype)serviceWithHost:(NSString *)host;
@end
#endif

NS_ASSUME_NONNULL_END

