// Code generated by gRPC proto compiler.  DO NOT EDIT!
// source: suggests.proto

#if !defined(GPB_GRPC_PROTOCOL_ONLY) || !GPB_GRPC_PROTOCOL_ONLY
#import "Suggests.pbrpc.h"
#import "Suggests.pbobjc.h"
#import <ProtoRPC/ProtoRPCLegacy.h>
#import <RxLibrary/GRXWriter+Immediate.h>

#import "Empty.pbobjc.h"
#import "Definitions.pbobjc.h"
#import "Peers.pbobjc.h"
#import "Scalapb.pbobjc.h"

@implementation Suggests

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wobjc-designated-initializers"

// Designated initializer
- (instancetype)initWithHost:(NSString *)host callOptions:(GRPCCallOptions *_Nullable)callOptions {
  return [super initWithHost:host
                 packageName:@"dialog"
                 serviceName:@"Suggests"
                 callOptions:callOptions];
}

- (instancetype)initWithHost:(NSString *)host {
  return [super initWithHost:host
                 packageName:@"dialog"
                 serviceName:@"Suggests"];
}

#pragma clang diagnostic pop

// Override superclass initializer to disallow different package and service names.
- (instancetype)initWithHost:(NSString *)host
                 packageName:(NSString *)packageName
                 serviceName:(NSString *)serviceName {
  return [self initWithHost:host];
}

- (instancetype)initWithHost:(NSString *)host
                 packageName:(NSString *)packageName
                 serviceName:(NSString *)serviceName
                 callOptions:(GRPCCallOptions *)callOptions {
  return [self initWithHost:host callOptions:callOptions];
}

#pragma mark - Class Methods

+ (instancetype)serviceWithHost:(NSString *)host {
  return [[self alloc] initWithHost:host];
}

+ (instancetype)serviceWithHost:(NSString *)host callOptions:(GRPCCallOptions *_Nullable)callOptions {
  return [[self alloc] initWithHost:host callOptions:callOptions];
}

#pragma mark - Method Implementations

#pragma mark LoadSuggests(RequestLoadSuggests) returns (ResponseLoadSuggests)

- (void)loadSuggestsWithRequest:(RequestLoadSuggests *)request handler:(void(^)(ResponseLoadSuggests *_Nullable response, NSError *_Nullable error))handler{
  [[self RPCToLoadSuggestsWithRequest:request handler:handler] start];
}
// Returns a not-yet-started RPC object.
- (GRPCProtoCall *)RPCToLoadSuggestsWithRequest:(RequestLoadSuggests *)request handler:(void(^)(ResponseLoadSuggests *_Nullable response, NSError *_Nullable error))handler{
  return [self RPCToMethod:@"LoadSuggests"
            requestsWriter:[GRXWriter writerWithValue:request]
             responseClass:[ResponseLoadSuggests class]
        responsesWriteable:[GRXWriteable writeableWithSingleHandler:handler]];
}
- (GRPCUnaryProtoCall *)loadSuggestsWithMessage:(RequestLoadSuggests *)message responseHandler:(id<GRPCProtoResponseHandler>)handler callOptions:(GRPCCallOptions *_Nullable)callOptions {
  return [self RPCToMethod:@"LoadSuggests"
                   message:message
           responseHandler:handler
               callOptions:callOptions
             responseClass:[ResponseLoadSuggests class]];
}

#pragma mark LoadMessageSuggests(RequestLoadMessageSuggests) returns (ResponseLoadMessageSuggests)

- (void)loadMessageSuggestsWithRequest:(RequestLoadMessageSuggests *)request handler:(void(^)(ResponseLoadMessageSuggests *_Nullable response, NSError *_Nullable error))handler{
  [[self RPCToLoadMessageSuggestsWithRequest:request handler:handler] start];
}
// Returns a not-yet-started RPC object.
- (GRPCProtoCall *)RPCToLoadMessageSuggestsWithRequest:(RequestLoadMessageSuggests *)request handler:(void(^)(ResponseLoadMessageSuggests *_Nullable response, NSError *_Nullable error))handler{
  return [self RPCToMethod:@"LoadMessageSuggests"
            requestsWriter:[GRXWriter writerWithValue:request]
             responseClass:[ResponseLoadMessageSuggests class]
        responsesWriteable:[GRXWriteable writeableWithSingleHandler:handler]];
}
- (GRPCUnaryProtoCall *)loadMessageSuggestsWithMessage:(RequestLoadMessageSuggests *)message responseHandler:(id<GRPCProtoResponseHandler>)handler callOptions:(GRPCCallOptions *_Nullable)callOptions {
  return [self RPCToMethod:@"LoadMessageSuggests"
                   message:message
           responseHandler:handler
               callOptions:callOptions
             responseClass:[ResponseLoadMessageSuggests class]];
}

#pragma mark SendSuggestAction(RequestSendSuggestAction) returns (Empty)

- (void)sendSuggestActionWithRequest:(RequestSendSuggestAction *)request handler:(void(^)(GPBEmpty *_Nullable response, NSError *_Nullable error))handler{
  [[self RPCToSendSuggestActionWithRequest:request handler:handler] start];
}
// Returns a not-yet-started RPC object.
- (GRPCProtoCall *)RPCToSendSuggestActionWithRequest:(RequestSendSuggestAction *)request handler:(void(^)(GPBEmpty *_Nullable response, NSError *_Nullable error))handler{
  return [self RPCToMethod:@"SendSuggestAction"
            requestsWriter:[GRXWriter writerWithValue:request]
             responseClass:[GPBEmpty class]
        responsesWriteable:[GRXWriteable writeableWithSingleHandler:handler]];
}
- (GRPCUnaryProtoCall *)sendSuggestActionWithMessage:(RequestSendSuggestAction *)message responseHandler:(id<GRPCProtoResponseHandler>)handler callOptions:(GRPCCallOptions *_Nullable)callOptions {
  return [self RPCToMethod:@"SendSuggestAction"
                   message:message
           responseHandler:handler
               callOptions:callOptions
             responseClass:[GPBEmpty class]];
}

@end
#endif
