// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: suggests.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30004
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30004 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class MessageSuggests;
@class Peer;
@class UUIDValue;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - SuggestsRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
GPB_FINAL @interface SuggestsRoot : GPBRootObject
@end

#pragma mark - MessageSuggests

typedef GPB_ENUM(MessageSuggests_FieldNumber) {
  MessageSuggests_FieldNumber_MessageId = 1,
  MessageSuggests_FieldNumber_SuggestsPayload = 2,
};

GPB_FINAL @interface MessageSuggests : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) UUIDValue *messageId;
/** Test to see if @c messageId has been set. */
@property(nonatomic, readwrite) BOOL hasMessageId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *suggestsPayload;

@end

#pragma mark - UpdateSuggests

typedef GPB_ENUM(UpdateSuggests_FieldNumber) {
  UpdateSuggests_FieldNumber_Clock = 1,
  UpdateSuggests_FieldNumber_PrevClock = 2,
  UpdateSuggests_FieldNumber_Peer = 3,
  UpdateSuggests_FieldNumber_MessageSuggests = 4,
};

GPB_FINAL @interface UpdateSuggests : GPBMessage

@property(nonatomic, readwrite) int64_t clock;

@property(nonatomic, readwrite) int64_t prevClock;

@property(nonatomic, readwrite, strong, null_resettable) Peer *peer;
/** Test to see if @c peer has been set. */
@property(nonatomic, readwrite) BOOL hasPeer;

@property(nonatomic, readwrite, strong, null_resettable) MessageSuggests *messageSuggests;
/** Test to see if @c messageSuggests has been set. */
@property(nonatomic, readwrite) BOOL hasMessageSuggests;

@end

#pragma mark - RequestLoadSuggests

typedef GPB_ENUM(RequestLoadSuggests_FieldNumber) {
  RequestLoadSuggests_FieldNumber_FromClock = 1,
  RequestLoadSuggests_FieldNumber_Peer = 2,
};

GPB_FINAL @interface RequestLoadSuggests : GPBMessage

@property(nonatomic, readwrite) int64_t fromClock;

@property(nonatomic, readwrite, strong, null_resettable) Peer *peer;
/** Test to see if @c peer has been set. */
@property(nonatomic, readwrite) BOOL hasPeer;

@end

#pragma mark - ResponseLoadSuggests

typedef GPB_ENUM(ResponseLoadSuggests_FieldNumber) {
  ResponseLoadSuggests_FieldNumber_Clock = 1,
  ResponseLoadSuggests_FieldNumber_SuggestsArray = 2,
  ResponseLoadSuggests_FieldNumber_MoreAvailable = 3,
};

GPB_FINAL @interface ResponseLoadSuggests : GPBMessage

@property(nonatomic, readwrite) int64_t clock;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<MessageSuggests*> *suggestsArray;
/** The number of items in @c suggestsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger suggestsArray_Count;

@property(nonatomic, readwrite) BOOL moreAvailable;

@end

#pragma mark - RequestLoadMessageSuggests

typedef GPB_ENUM(RequestLoadMessageSuggests_FieldNumber) {
  RequestLoadMessageSuggests_FieldNumber_Peer = 1,
  RequestLoadMessageSuggests_FieldNumber_MessageIdsArray = 2,
};

GPB_FINAL @interface RequestLoadMessageSuggests : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) Peer *peer;
/** Test to see if @c peer has been set. */
@property(nonatomic, readwrite) BOOL hasPeer;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<UUIDValue*> *messageIdsArray;
/** The number of items in @c messageIdsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger messageIdsArray_Count;

@end

#pragma mark - ResponseLoadMessageSuggests

typedef GPB_ENUM(ResponseLoadMessageSuggests_FieldNumber) {
  ResponseLoadMessageSuggests_FieldNumber_MessageSuggestsArray = 1,
};

GPB_FINAL @interface ResponseLoadMessageSuggests : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<MessageSuggests*> *messageSuggestsArray;
/** The number of items in @c messageSuggestsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger messageSuggestsArray_Count;

@end

#pragma mark - RequestSendSuggestAction

typedef GPB_ENUM(RequestSendSuggestAction_FieldNumber) {
  RequestSendSuggestAction_FieldNumber_RequestId = 1,
  RequestSendSuggestAction_FieldNumber_SuggestId = 2,
  RequestSendSuggestAction_FieldNumber_Peer = 3,
  RequestSendSuggestAction_FieldNumber_Payload = 4,
};

GPB_FINAL @interface RequestSendSuggestAction : GPBMessage

@property(nonatomic, readwrite) int64_t requestId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *suggestId;

@property(nonatomic, readwrite, strong, null_resettable) Peer *peer;
/** Test to see if @c peer has been set. */
@property(nonatomic, readwrite) BOOL hasPeer;

@property(nonatomic, readwrite, copy, null_resettable) NSString *payload;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
